version: "3.8"

services:
  db:
    image: "postgres:latest"
    restart: always
    ports:
      - "3000:5432"
    environment:
      - POSTGRES_DB=taskmanager_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

